In [57]:
import pandas as pd

df = pd.read_csv("BCM.csv")
df = df.set_index("Folio")
df.columns

Index(['Tipo de Servicio Requerido', 'Fecha de Captura', 'Hora de Captura',
       'Hora de Asignacion de Tecnico', 'Inicio Reparacion',
       'Termino Reparacion', 'Total de Minutos', 'Reporto', 'Linea', 'Proceso',
       'Equipo', 'Subequipo', 'Turno', 'Tipo de Mantenimiento Asignado',
       'Técnico Asignado', 'Supervisor de Mantenimiento', 'Operador de Datos',
       'Descripcion del Problema', 'Modo de Falla', 'Estatus',
       'Equipo critico', 'BU', 'Mes'],
      dtype='object')

In [63]:
print(df["Reporto"].unique().shape)
print(df["Técnico Asignado"].unique().shape)
print(df["Supervisor de Mantenimiento"].unique().shape)

(1104,)
(328,)
(95,)

In [68]:
df_red = df[["Reporto","Técnico Asignado"]]
df_red = df_red[df["Reporto"].isna() != True]
df_red = df_red[df["Técnico Asignado"].isna() != True]
df_red

C:\Users\chccr\AppData\Local\Temp\ipykernel_25344\3267349122.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_red = df_red[df["Técnico Asignado"].isna() != True]

                      Reporto              Técnico Asignado
Folio
220103001       Andres Rendon        Aquilino Ortiz Chairez
220103002       Andres Rendon    Jose Moises Gallegos Auces
220103003         Jorge Gaona      Juan Omar Garcia  Pineda
220103004       Andres Rendon  Jonathan Martinez Victoriano
220103005  Roberto de la Rosa       Nicolas Alejo Hernandez
...                       ...                           ...
220727079       Ricardo Reyes                  Carlos Lopez
220727082      Raymundo Pérez   Jesus Antonio Lopez Segovia
220727084      Evelio Montoya    Harley Aray Martinez Reyna
220727085     Alfredo Robledo     Jesus Oscar Torres Garcia
220727087       Ricardo Reyes     Jesus Oscar Torres Garcia

[33208 rows x 2 columns]

In [69]:
df_red.isna().sum()

Reporto             0
Técnico Asignado    0
dtype: int64

In [ ]:
def intersection(lst1, lst2):
    """Retorna una lista de los clientes comunes entre dos agentes.
    Argumentos de entrada
    lst1: ingresa la lista de clientes del agente1
    lst2: ingresa la lista de clientes del agente2
    """
    lst1 = set(lst1)
    lst2 = set(lst2)
    return list(lst1.intersection(lst2))

In [ ]:
# Prueba de la función
print("Intersecciones de ({}, {})".format(agents[464], agents[321]))
common_client = intersection(new_df[new_df["AGENT ID"] == agents[464]]["ClientID"],
                             new_df[new_df["AGENT ID"] == agents[321]]["ClientID"])
print(common_client)

In [ ]:
table_list = []
x = 0
n = len(agents)

# Itera sobre todas las combinaciones de agentes
for i in range(n):
    for j in range(i+1, n):
        # Encuentra los clientes en común
        common_client = intersection(new_df[new_df["AGENT ID"] == agents[i]]["ClientID"],
                                     new_df[new_df["AGENT ID"] == agents[j]]["ClientID"])
        # Cuenta los clientes en común
        x = len(common_client)
        # Agrega a la tabla si hay al menos un cliente en comun
        if x > 0:
            table_list.append([agents[i], agents[j], x])
    # Imprime cada 10 agentes el estatus del progreso
    if i % 10 == 0:
        print("\rAgentes analizados: {}/{}".format(i, n), end="")

# Imprime y organiza la tabla
table = pd.DataFrame(table_list, columns=["AGENTID1", "AGENTID2", "CLIENTS"])
table.sort_values("CLIENTS", ascending=False)

In [ ]:
from itertools import combinations

table = pd.DataFrame(columns=["AGENTS"])

# Itera sobre todos los clientes
for client in list_clients:
    # Filtra dataframe por cliente
    client_df = new_df[new_df["ClientID"] == client]
    # Enlista todos los agentes que comparten un cliente
    agent_per_client = client_df["AGENT ID"].sort_values().unique()
    # Crea dataframe con todas las combinaciones de los agentes
    agent_combinations = pd.DataFrame(
        {"AGENTS": list(combinations(agent_per_client, 2))})
    # Añade la columna cliente con el cliente que comparten estas combinaciones
    agent_combinations["CLIENT"] = client
    # Concatena los dataframes generados
    table = pd.concat([table, agent_combinations])

# Agrupa la tabla por combinaciones de clientes
table = table.groupby("AGENTS").count()
# Convierte la combinación de agente en 2 listas
two_lists = list(zip(*table.index))
table["AGENT1"] = list(two_lists[0])
table["AGENT2"] = list(two_lists[1])
# Elimina la columna AGENTS que contiene la combinación de agentes
table.reset_index(inplace=True)
table.drop("AGENTS", axis=1, inplace=True)
# Reconfigura la tabla
table = table[["AGENT1", "AGENT2", "CLIENT"]]
table = table.sort_values("CLIENT", ascending=False)
table.head(10)

In [50]:
df = df[['Tipo de Servicio Requerido','Hora de Captura',
         'Total de Minutos','Linea','Proceso','Equipo',
         'Turno','Tipo de Mantenimiento Asignado',
         'Equipo critico']]
df

,Tipo de Servicio Requerido,Hora de Captura,Total de Minutos,Linea,Proceso,Equipo,Turno,Tipo de Mantenimiento Asignado,Equipo critico
Folio,,,,,,,,,
220103001,Requerimiento,3/1/2022 6:23:21,7,L1,Termoformado,Termoformadora Comi 1,T1,Mecanico,0
220103002,Requerimiento,3/1/2022 6:24:58,37,L1,Termoformado,Termoformadora Comi 1,T1,Taller Herramientas,0
220103003,Requerimiento,3/1/2022 6:32:41,40,L4,Perfilado,Perfiladora Gabinetes L4,T1,Taller Herramientas,0
220103004,Requerimiento,3/1/2022 6:35:13,51,L1,Termoformado,Termoformadora Comi 1,T1,Eléctronico,0
220103005,Requerimiento,3/1/2022 6:42:28,14,Fabricacion,Pinturas,Cuarto de Preparacion de Pinturas,T1,Mecanico,0
...,...,...,...,...,...,...,...,...,...
220727079,Ajustes,27/7/2022 16:27:19,15,L2,Espumado,Inyectora Puertas Cannon A,T1,Mecanico,1
220727082,Ajustes,27/7/2022 16:44:30,47,L2,Espumado,Espumado Gabinetes L2,T1,Taller Herramientas,1
220727084,Falla,27/7/2022 17:01:18,32,L4,Línea de Ensamble,Bahía R-600,T1,Eléctronico,0
220727085,Cambio modelo,27/7/2022 17:01:35,25,L4,Termoformado,Pirceadora Rc FDBM L4,T1,Taller Herramientas,0
220727087,Ajustes,27/7/2022 17:27:38,12,L2,Espumado,Inyectora Puertas Cannon A,T1,Taller Herramientas,1

In [38]:
import numpy as np

In [55]:
line_dict = {"L 1":"L1","L 2":"L2","L 3":"L3","L 4":"L4"}
shift_dict = {"T 1":"T1","T 2":"T2","T 3":"T3","T 4":"T4"}
critico_dict = {np.nan:0,"No critico":0,"Critico":1}
df.loc[:,"Linea"] = df.loc[:,"Linea"].replace(line_dict)
df.loc[:,"Turno"] = df.loc[:,"Turno"].replace(shift_dict)
df.loc[:,"Equipo critico"] = df.loc[:,"Equipo critico"].replace(critico_dict)
df = df[df["Tipo de Servicio Requerido"].isna() != True]
df = df[df["Total de Minutos"].isna() != True]
df = df[df["Linea"].isna() != True]
df = df[df["Tipo de Mantenimiento Asignado"].isna() != True]
df = df[df["Total de Minutos"] != "Pendiente"]

In [56]:
df

,Tipo de Servicio Requerido,Hora de Captura,Total de Minutos,Linea,Proceso,Equipo,Turno,Tipo de Mantenimiento Asignado,Equipo critico
Folio,,,,,,,,,
220103001,Requerimiento,3/1/2022 6:23:21,7,L1,Termoformado,Termoformadora Comi 1,T1,Mecanico,0
220103002,Requerimiento,3/1/2022 6:24:58,37,L1,Termoformado,Termoformadora Comi 1,T1,Taller Herramientas,0
220103003,Requerimiento,3/1/2022 6:32:41,40,L4,Perfilado,Perfiladora Gabinetes L4,T1,Taller Herramientas,0
220103004,Requerimiento,3/1/2022 6:35:13,51,L1,Termoformado,Termoformadora Comi 1,T1,Eléctronico,0
220103005,Requerimiento,3/1/2022 6:42:28,14,Fabricacion,Pinturas,Cuarto de Preparacion de Pinturas,T1,Mecanico,0
...,...,...,...,...,...,...,...,...,...
220727079,Ajustes,27/7/2022 16:27:19,15,L2,Espumado,Inyectora Puertas Cannon A,T1,Mecanico,1
220727082,Ajustes,27/7/2022 16:44:30,47,L2,Espumado,Espumado Gabinetes L2,T1,Taller Herramientas,1
220727084,Falla,27/7/2022 17:01:18,32,L4,Línea de Ensamble,Bahía R-600,T1,Eléctronico,0
220727085,Cambio modelo,27/7/2022 17:01:35,25,L4,Termoformado,Pirceadora Rc FDBM L4,T1,Taller Herramientas,0
220727087,Ajustes,27/7/2022 17:27:38,12,L2,Espumado,Inyectora Puertas Cannon A,T1,Taller Herramientas,1

In [47]:
df.isna().sum()

Tipo de Servicio Requerido          0
Hora de Captura                     0
Total de Minutos                    0
Linea                               0
Proceso                            38
Equipo                            422
Turno                               0
Tipo de Mantenimiento Asignado      0
Estatus                             0
Equipo critico                      0
dtype: int64

In [10]:
df["Linea"] = df["Linea"].astype("category")
df["Linea"].cat.codes

Folio
220103001    1
220103002    1
220103003    4
220103004    1
220103005    0
            ..
220727084    8
220727085    8
220727086    0
220727087    6
220727088    8
Length: 33435, dtype: int8

In [12]:
df["Linea"]

Folio
220103001            L 1
220103002            L 1
220103003            L 4
220103004            L 1
220103005    Fabricacion
                ...
220727084             L4
220727085             L4
220727086    Fabricacion
220727087             L2
220727088             L4
Name: Linea, Length: 33435, dtype: category
Categories (10, object): ['Fabricacion', 'L 1', 'L 2', 'L 3', ..., 'L2', 'L3', 'L4', 'Planta']